# Generated by Django 5.1.3 on 2024-11-30 03:50

import datetime
import django.db.models.deletion
import hospital.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cirurgia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('procedimento', models.CharField(max_length=50)),
                ('data_cirurgia', models.DateTimeField()),
                ('local', models.TextField()),
                ('medico_cirurgiao', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo_consulta', models.CharField(max_length=50)),
                ('diagnostico', models.TextField()),
                ('prescricao', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Exame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_exame', models.CharField(max_length=50)),
                ('resultado', models.TextField(blank=True, null=True)),
                ('data_exame', models.DateTimeField()),
                ('medico_solicitante', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to=hospital.models.paciente_directory_path)),
                ('nome', models.CharField(max_length=200)),
                ('data_nascimento', models.DateField()),
                ('sexo', models.CharField(choices=[('MS', 'Masculino'), ('FM', 'Feminino')], max_length=50)),
                ('cpf', models.CharField(blank=True, max_length=14)),
                ('rg', models.CharField(max_length=20)),
                ('telefone', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('endereco', models.CharField(max_length=50)),
                ('cidade', models.CharField(max_length=50)),
                ('estado', models.CharField(max_length=50)),
                ('cep', models.CharField(max_length=50)),
                ('numero_carteira', models.CharField(max_length=50)),
                ('data_cadastro', models.DateTimeField(default=datetime.datetime(2024, 11, 30, 3, 50, 54, 214015))),
                ('status', models.CharField(choices=[('AT', 'Ativo'), ('IN', 'Inativo')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Planos',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tratamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_tratamento', models.CharField(max_length=50)),
                ('frequencia', models.CharField(max_length=50)),
                ('duracao', models.CharField(max_length=50)),
                ('avaliacao_periodica', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='HistoricoMedico',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('data', models.DateTimeField(default=datetime.datetime(2024, 11, 30, 3, 50, 54, 214836))),
                ('descricao', models.TextField(blank=True, null=True)),
                ('anexos', models.FileField(blank=True, null=True, upload_to=hospital.models.anexos_directory_path)),
                ('paciente_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.paciente')),
            ],
        ),
        migrations.AddField(
            model_name='paciente',
            name='plano_saude',
            field=models.ManyToManyField(to='hospital.planos'),
        ),
    ]
