# Generated by Django 5.1.3 on 2024-11-30 04:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0003_rename_planos_plano_alter_historicomedico_data_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicomedico',
            name='descricao',
        ),
        migrations.AddField(
            model_name='historicomedico',
            name='cirurgia',
            field=models.ManyToManyField(blank=True, null=True, to='hospital.cirurgia'),
        ),
        migrations.AddField(
            model_name='historicomedico',
            name='consulta',
            field=models.ManyToManyField(blank=True, null=True, to='hospital.consulta'),
        ),
        migrations.AddField(
            model_name='historicomedico',
            name='exame',
            field=models.ManyToManyField(blank=True, null=True, to='hospital.exame'),
        ),
        migrations.AddField(
            model_name='historicomedico',
            name='tratamento',
            field=models.ManyToManyField(blank=True, null=True, to='hospital.tratamento'),
        ),
        migrations.AlterField(
            model_name='historicomedico',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 30, 4, 18, 20, 919206)),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='data_cadastro',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 30, 4, 18, 20, 918251)),
        ),
    ]
