# Generated by Django 5.1.3 on 2024-11-30 18:01

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0005_cirurgia_paciente_consulta_paciente_exame_paciente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicomedico',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 30, 18, 1, 52, 142534, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='historicomedico',
            name='paciente',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='hospital.paciente'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='data_cadastro',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 30, 18, 1, 52, 126114, tzinfo=datetime.timezone.utc)),
        ),
    ]
