# Generated by Django 5.1.3 on 2024-11-30 20:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0007_alter_historicomedico_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicomedico',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 30, 20, 18, 36, 146561, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='data_cadastro',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 30, 20, 18, 36, 144257, tzinfo=datetime.timezone.utc)),
        ),
    ]
