# Generated by Django 5.1.3 on 2024-11-30 20:20

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0008_alter_historicomedico_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cirurgia',
            name='paciente',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='hospital.paciente'),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='paciente',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='hospital.paciente'),
        ),
        migrations.AlterField(
            model_name='exame',
            name='paciente',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='hospital.paciente'),
        ),
        migrations.AlterField(
            model_name='historicomedico',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 30, 20, 20, 4, 484177, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='data_cadastro',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 30, 20, 20, 4, 481882, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='tratamento',
            name='paciente',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='hospital.paciente'),
        ),
    ]
