# Generated by Django 5.1.3 on 2024-11-30 20:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0009_alter_cirurgia_paciente_alter_consulta_paciente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plano',
            name='nome',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='historicomedico',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 30, 20, 55, 39, 26776, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='data_cadastro',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 30, 20, 55, 39, 24522, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='plano',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
