# Generated by Django 5.1.3 on 2025-02-04 23:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0010_plano_nome_alter_historicomedico_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicomedico',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 4, 23, 7, 54, 870543, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='data_cadastro',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 4, 23, 7, 54, 868062, tzinfo=datetime.timezone.utc)),
        ),
    ]
